[package]
name = "liblustreapi"
version = "0.1.0"
edition = "2021"
license = "LGPL2"
repository = "https://github.com/cea-hpc/coordinatool"

[dependencies]
anyhow = "1.0.95"

[build-dependencies]
bindgen = "0.71.1"
